### ISSUE TITLE
Deploy asset tracking api

### ISSUE THREAD

**Issue by hanheuljo** [qsib-cbie/asset-tracking-api#23]
- I do think that most of these projects will use the same structure since we have a tendency to upload blob data to S3 rather than changing schemas/endpoints to match a specific project need
- I think there will be handful of users involved in deployment, ie you, me, other new hire. I am looking for something that is not clicky in the UI, since that will likely change as time goes on and we rarely revisit deployments. Single/short commands to reach deployment are highly desired for that reason.
- Yes, this will be used to collect data and we will have many complaints if there is down time w/o visibility. I would like to automatically deploy distinct instances of stacks like what I have deployed. Currently, I have manually deployed
    - HA Load Balancer (nginx based service)
    - Multiple Compute VMs with HTTP server (monitored by LogDNA and Dead Man's Snitch)
    - Redundancy and Load Balancer config allows me to do manual rolling upgrades w/o down time
    - HA Postgres w/ backups
    - Spaces (essentially S3)
- Yes, we need data backups. Loosing study data is extremely detrimental; it is one thing if the app tells you it failed to upload but something else entirely if the data was uploaded and can't be found.
- It would be nice to have separate buckets for backups of the database, the data S3 bucket, and snapshots of the http server VMs.

**Comment by trueb2** [comment]
This has been abandoned
